apiVersion: v1
kind: Pod
metadata: 
  name: my-app
spec:
  containers:
  - name: nginx
    image: nginx  
    volumeMounts:
    - name: app-data-claim
      mountPath: /usr/share/nginx/html
  volumes:
  - name: app-data-claim
    persistentVolumeClaim:
      claimName: test-pv  



